### ISSUE TITLE
Does not connect to Materialize 0.3.0

### ISSUE THREAD

**Issue by awang** [MaterializeInc/metabase-materialize-driver#11]
I'm getting the following error when trying to connect:

`ERROR: Parse error: SELECT n.nspname = ANY(current_schemas(true)), n.nspname, t.typname FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1 ^^^^^^^^^^^^^^^ Expected SELECT, VALUES, or a subquery in the query body, found: current_schemas`

So far, I've tested against Materialized 0.3.0 (both Ubuntu binary and mac homebrew).  I've also tried the BI demo from 0.2.2 (which sort-of works) against Materialized 0.3.0 (which doesn't work)

**Comment by benesch** [comment]
Is it possible you selected the "PostgreSQL" driver instead of the "Materialize" driver when you created the connection?

**Comment by awang** [comment]
Nope, I just double-checked and it's "Materialize", unfortunately.  Btw, I'm using the prebuilt 0.0.5 materialize-driver.jar (e09f01d)

**Comment by benesch** [comment]
Hmm, that's definitely strange. That query that is getting issued strongly implies to me that the Materialize driver isn't getting chosen. @quodlibetor or @JLDLaughlin may need to take a look. FWIW our CI tests the Metabase Docker image (https://github.com/MaterializeInc/metabase-materialize-driver#with-docker) with the latest tip of Materialize on every commit, so possibly it's just something about the JAR that's broken.

**Comment by bobbyiliev** [comment]
Closing this issue as it is no longer applicable for the new version of the driver.
