### ISSUE TITLE
allow jdbc string options

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/metabase-materialize-driver#17]
https://github.com/metabase/metabase/blob/7f4addcf97c207db89b4254db8592c8181e1a0d5/src/metabase/driver/common.clj#L105

Allows extra jdbc options when connecting, which is required for, say, custom certs when connecting to cloud.

**Comment by andrioni** [comment]
Closing this issue since we are deprecating this driver and the vanilla Postgres driver supports JDBC options.
